name: gemini_app
description: "A Sample Flutter App to investigate google_generative_ai."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  equatable: ^2.0.5
  flutter_markdown: ^0.7.3
  flutter_bloc: ^8.1.6
  google_generative_ai: ^0.4.3
  http: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true